# Production environment configuration
spring:
  profiles:
    active: prod

  # Production database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-host}:${DB_PORT:5432}/${DB_NAME:prod_db}?currentSchema=${SERVICE_SCHEMA:inventory}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  # JPA configuration for production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka configuration for production
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:kafka-cluster:9092}
    consumer:
      group-id: ${SERVICE_NAME}-prod
      auto-offset-reset: earliest
      session-timeout-ms: 30000
    producer:
      acks: all
      retries: 3
      batch-size: 16384

# Eureka client configuration for production
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-cluster:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30

# Management endpoints for production (limited exposure)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

# Logging configuration for production
logging:
  level:
    com.eplatform.b2b: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /logs/${SERVICE_NAME}.log

# Custom production properties
app:
  environment: production
  version: ${project.version}

# Security configuration for production
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
