server:
  port: 8150
spring:
  application:
    name: supplier-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db?currentSchema=supplier
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
